version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root@123'
            MYSQL_USER: 'kwta_user'
            MYSQL_PASSWORD: 'kwta@123'
            MYSQL_DATABASE: 'kwta'
        volumes:
            - ./mysqldata:/var/lib/mysql
        ports:
            - 33060:3306
volumes:
    mysqldata: {}