version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
    php:
        image: php:fpm
        volumes:
            - ./app:/app